Fix error after `systemctl restart noc` in main->setup->csv export/import
UNHANDLED EXCEPTION (2024-02-05 15:01:28.084065)
PROCESS: ./services/web/service.py
VERSION: 23.1+master.798.10ea93fa
BRANCH: master CHANGESET: 10ea93fa
ERROR FINGERPRINT: f8128f79-1582-55e3-851a-839a2521f178
WORKING DIRECTORY: /opt/noc
EXCEPTION: <class 'AttributeError'> 'str' object has no attribute '_meta'
START OF TRACEBACK
------------------------------------------------------------------------
File: services/web/apps/main/csv/views.py (Line: 155)
Function: view_import
  148                     return self.response_redirect(form.cleaned_data["referer"])
  149             else:
  150                 form = self.ImportForm({"referer": request.META.get("HTTP_REFERER", "/")})
  151             # Prepare fields description
  152             fields = []
  153             for name, required, rel, rname in get_model_fields(m):
  154                 if rel:
  155 ==>                 if isinstance(rel._meta, dict):
  156                         r = ["%s.%s" % (rel._meta["collection"], rname)]
  157                     else:
  158                         db_table = rel._meta.db_table
  159                         r = ['%s."id"' % db_table]
  160                         if rname != "id":
  161                             r = ['%s."%s"' % (db_table, rname)] + r
Variables:
               model = 'ManagedObject'
                 app = 'sa'
                form = <ImportForm bound=True, valid=Unknown, fields=(file;resolve;referer)>
              fields =
[('name', True, ''),
 ('container', False, 'noc.objects.id'),
 ('administrative_domain',
  True,
  'sa_administrativedomain."name" or sa_administrativedomain."id"'),
 ('segment', True, 'noc.networksegments.name'),
 ('pool', True, 'noc.pools.name'),
 ('project', False, 'project_project."code" or project_project."id"'),
 ('state', False, 'states.id'),
 ('state_changed', False, ''),
 ('expired', False, ''),
 ('last_seen', False, ''),
 ('first_discovered', False, ''),
 ('fm_pool', False, 'noc.pools.name'),
 ('profile', False, 'noc.profiles.name'),
 ('vendor', False, 'noc.vendors.name'),
 ('platform', False, 'noc.platforms.full_name'),
 ('version', False, 'noc.firmwares.id'),
 ('next_version', False, 'noc.firmwares.id'),
 ('object_profile',
  True,
  'sa_managedobjectprofile."name" or sa_managedobjectprofile."id"'),
 ('description', False, ''),
 ('auth_profile', False, 'sa_authprofile."name" or sa_authprofile."id"'),
 ('scheme', True, ''),
 ('address', True, ''),
 ('port', False, ''),
 ('user', False, ''),
 ('password', False, ''),
 ('super_password', False, ''),
 ('remote_path', False, ''),
 ('trap_source_type', False, ''),
 ('trap_source_ip', False, ''),
 ('syslog_source_type', False, ''),
 ('syslog_source_ip', False, ''),
 ('trap_community', False, ''),
 ('snmp_ro', False, ''),
 ('snmp_rw', False, ''),
 ('snmp_rate_limit', False, ''),
 ('access_preference', False, ''),
 ('fqdn', False, ''),
 ('address_resolution_policy', False, ''),
 ('l2_domain', False, 'l2domains.name'),
 ('vrf', False, 'ip_vrf."name" or ip_vrf."id"')]
                name = 'cpe_id'
            required = False
                 rel = 'inv.CPE'
               rname = 'global_id'
                   r = ['ip_vrf."name"', 'ip_vrf."id"']
            db_table = 'ip_vrf'
                   m = <class 'noc.sa.models.managedobject.ManagedObject'>
             request = <WSGIRequest: GET '/main/csv/import/sa.ManagedObject/'>
                self =
<noc.services.web.apps.main.csv.views.CSVApplication object at 0x7fed6596b910>
------------------------------------------------------------------------
File: services/web/base/site.py (Line: 231)
Function: inner
  224                                 a = orjson.loads(request.body)
  225                             else:
  226                                 a = {k: v[0] if len(v) == 1 else v for k, v in request.POST.lists()}
  227                         elif request.method == "GET":
  228                             a = {k: v[0] if len(v) == 1 else v for k, v in request.GET.lists()}
  229                         app_logger.debug("API %s %s %s", request.method, request.path, a)
  230                     # Call handler
  231 ==>                 r = v(request, *args, **kwargs)
  232                     # Dump SQL statements
  233                     if self.log_sql_statements:
  234                         from django.db import connections
  235
  236                         tsc = 0
  237                         sc = defaultdict(int)
Variables:
             request = <WSGIRequest: GET '/main/csv/import/sa.ManagedObject/'>
                args = ()
              kwargs = {'model': 'sa.ManagedObject'}
                   v =
<bound method CSVApplication.view_import of <noc.services.web.apps.main.csv.views.CSVApplication object at 0x7fed6596b910>>
     to_log_api_call = False
          app_logger = <Logger main.csv (INFO)>
                  nq = <function Site.site_view.<locals>.inner.<locals>.nq at 0x7fed62ff1dc0>
       DictParameter = <class 'noc.sa.interfaces.base.DictParameter'>
  InterfaceTypeError = <class 'ValueError'>
    PermissionDenied = <class 'noc.services.web.base.access.PermissionDenied'>
                 app =
<noc.services.web.apps.main.csv.views.CSVApplication object at 0x7fed6596b910>
                self = <noc.services.web.base.site.Site object at 0x7fed77debc10>
            view_map =
{'DELETE': <bound method CSVApplication.view_import of <noc.services.web.apps.main.csv.views.CSVApplication object at 0x7fed6596b910>>,
 'GET': <bound method CSVApplication.view_import of <noc.services.web.apps.main.csv.views.CSVApplication object at 0x7fed6596b910>>,
 'POST': <bound method CSVApplication.view_import of <noc.services.web.apps.main.csv.views.CSVApplication object at 0x7fed6596b910>>,
 'PUT': <bound method CSVApplication.view_import of <noc.services.web.apps.main.csv.views.CSVApplication object at 0x7fed6596b910>>}
------------------------------------------------------------------------
END OF TRACEBACK